# Ashkan Bigdeli 
#
# 2/7/2018
#
#
# This script appends the MasterVariant File with CNV results generated by a sample in the 
# halo_v1.3 Pipeline. This process is ugly and should be deprecated, but for now
# this is how we will present data to be curated in the filemaker "database".

import sys, itertools



# onco_append
#
# @param1 = variants is the onco_parsed.tsv file output from Sv2 pipeline.
# @param2 = pre-parsed calls made by CNVkit
# @param3 = annotated regions of CNV (for transcript retrieval
#
# Takes in filemaker upload ready variants and appends copy number
# variants with transcript id pulled in from SNPEff.
def onco_append(variants,cnv,snpeff):
    with open(variants, 'a+') as master_var:
        with open(cnv, 'r') as cnv:
            # skip first line, create a counter
            line = cnv.readline()
            variant_count = 0
            for line in cnv:
                line = line.strip()
                values = line.split('\t')
                

                # assign relevant data for CNVs
                sample_name = values[0]
                chrom = values[2]
                start_pos = values[3]
                end_pos = values[4]
                gene = values[1]
                cn = values[6]
                depth = int(float(values[7]))
                probes = values[8]
                weight = int(float(values[9]))
                onc_type = "CNV"

                # retrieve transcript from annotation file using the chrom, start, end
                with open(snpeff, 'r') as snpeff_in:
                    for line in itertools.islice(snpeff_in, 2, None): #skip the first 3 lines
                        line = line.strip()
                        values = line.split('\t')
                        if (chrom == ('chr' + values[0])) and (start_pos == values[1]) and (end_pos == values[2]):
                            anno = values[3].split('|')
                            transcript = anno[2] 
                                    
                     
                variant_count = variant_count + 1 
                master_var.write(sample_name + '\t' + chrom + '\t' + start_pos + '\t' + 'NL' + '\t' + 'CNG' + '\t' + onc_type + '\t' + 'NA' + '\t' + '' + '\t' +
                             str(depth) + '\t' + 'NA' + '\t' + '' + '\t' + gene + '\t' + 'NA' + '\t' + transcript + '\t' + 'NA' + '\t' + '' +
                             '\t' + onc_type + '\t' + 'NA' + '\t' + '' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' +
                             '\t' + '' + '\t' + '' + '\t' + '' + '\t' + onc_type + '\t' + gene + '\t' + onc_type + '\t' + transcript +
                             '\t' + '' + '\t' + '' + '\t' + chrom + '\t' + start_pos + '\t' + '' + '\t' + '' + '\t' + '' + '\t' + '' +
                             '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + '' + '\t' + '' + '\t' + '' + '\t' + '' + '\t' +
                             '' + '\t' + '' + '\t' + '' + '\t' + onc_type + '\t' + str(depth) + '\t' + str(probes) + '\t' + str(("%.2f" % weight)) + '\t' + cn + '\t'
                             + gene + '\t' + '' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' +
                             '\t' + 'NA' + '\t' + start_pos + '\t' + end_pos + '\t' + '' + '\t' + '' + '\t' + '' + '\t' + '' +
                             '\t' + '' + '\t' + 'NA' + '\t' + '' + '\t' + '' + '\t' + '' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' +
                             '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' +
                             '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + '' + '\t' + '' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' +
                             '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' +
                             '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' +
                             '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' +
                             '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' +
                             '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' +
                             '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' +
                             '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' +
                             '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' +
                             '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + '' +
                            '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\n')

            # add blank values to variant file for no variants
            if variant_count == 0:
                print_normals(sample_name, variants_file)


# print_normals
#
# @param1 = sample name
# @param2 = file to store variant output
#
# If a variant shows no cnv blank information should be input
# for the variant review to acknowledge the sample is indeed normal 
# and output in legacy format.
def print_normals(sample_name, variants_file):
           with open (variants_file, 'a') as master_var:
                 master_var.write(sample_name + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'No Known CNV' + '\t' + 'Normal' + '\t' + 'NA' + '\t' + 'NA' + '\t' +
                             'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' +
                             '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' +
                             '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'No Known CNV' + '\t' + 'NA' +
                             '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'No Known CNV' + '\t' + 'NA' +
                             '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' +
                             'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'Normal' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t'
                             + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' +
                             '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' +
                             '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' +
                             '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' +
                             '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' +
                             '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' +
                             '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' +
                             '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' +
                             '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' +
                             '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' +
                             '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' +
                             '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' +
                             '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' +
                             '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' +
                            '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\t' + 'NA' + '\n')
def main():
    
    # Take in variants produced by Sv2, CNVkit, and annotated SNPEff regions
    variants = sys.argv[1]
    cnv=sys.argv[2]
    snpeff=sys.argv[3]
    onco_append(variants,cnv,snpeff)


main()

